package com.jam3yati.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.content.ClipData;
import androidx.core.content.FileProvider;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private static final String SUPABASE_URL = "https://irknxbbmhibutriaagfw.supabase.co";
    private static final String SUPABASE_KEY = "sb_publishable__YUC1HHjJAtdYqQUcwecgQ_H0-RuL1g";
    private SharedPreferences prefs;
    private String accessToken="", userId="", role="member";
    private Handler main = new Handler(Looper.getMainLooper());
    private LinearLayout root, content; private TextView status, title;
    private final int TEAL=Color.rgb(15,118,110), DARK=Color.rgb(23,32,51), BG=Color.rgb(245,247,251);

    @Override public void onCreate(Bundle b){
        super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(11,94,87));
        prefs=getSharedPreferences("jam3yati",MODE_PRIVATE);
        accessToken=prefs.getString("access_token",""); userId=prefs.getString("user_id","");
        role=prefs.getString("role","member");
        if(accessToken.isEmpty()) login(); else dashboard();
    }
    private TextView tv(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setPadding(16,12,16,12);v.setGravity(Gravity.RIGHT);return v;}
    private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);e.setPadding(16,8,16,8);e.setGravity(Gravity.RIGHT);return e;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);return b;}
    private LinearLayout box(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(16,14,16,14);x.setBackgroundColor(Color.WHITE);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(8,6,8,6);x.setLayoutParams(p);return x;}
    private void base(String t){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);title=tv(t,22,Color.WHITE);title.setBackgroundColor(TEAL);title.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);title.setPadding(20,20,20,20);root.addView(title);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));status=tv("",12,Color.DKGRAY);root.addView(status);setContentView(root);}
    private void nav(){LinearLayout n=new LinearLayout(this);n.setPadding(4,2,4,2);String[] labels={"الرئيسية","الجمعيات","الأعضاء","الدورات","الأقساط","الدفعات","الإشعارات","التقارير"};View.OnClickListener[] ls={v->dashboard(),v->associations(),v->members(),v->cycles(),v->installments(),v->payments(),v->notifications(),v->reports()};for(int i=0;i<labels.length;i++){Button b=btn(labels[i]);b.setOnClickListener(ls[i]);n.addView(b,new LinearLayout.LayoutParams(-2,-2));}HorizontalScrollView hs=new HorizontalScrollView(this);hs.addView(n);root.addView(hs,1);}
    private void login(){base("جمعياتي • إدارة الجمعيات المالية");LinearLayout c=box();c.addView(tv("تسجيل الدخول",22,DARK));EditText e=input("البريد الإلكتروني");EditText p=input("كلمة المرور");p.setInputType(129);c.addView(e);c.addView(p);Button b=btn("دخول آمن");c.addView(b);c.addView(tv("الحسابات والصلاحيات تتم عبر Supabase Auth وRLS.",13,Color.GRAY));content.addView(c);b.setOnClickListener(v->{String em=e.getText().toString().trim(),pw=p.getText().toString();if(em.isEmpty()||pw.isEmpty()){toast("أدخل البريد وكلمة المرور");return;}b.setEnabled(false);new Thread(()->{try{JSONObject j=new JSONObject();j.put("email",em);j.put("password",pw);ApiResult r=req("POST","/auth/v1/token?grant_type=password",j.toString(),"");if(r.ok()){JSONObject x=new JSONObject(r.body);JSONObject u=x.getJSONObject("user");accessToken=x.getString("access_token");userId=u.getString("id");prefs.edit().putString("access_token",accessToken).putString("user_id",userId).apply();loadRoleAndOpen();}else main.post(()->{b.setEnabled(true);toast(error(r.body));});}catch(Exception ex){main.post(()->{b.setEnabled(true);toast("تعذر الاتصال: "+ex.getMessage());});}}).start();});}
    private void loadRoleAndOpen(){new Thread(()->{try{ApiResult r=req("GET","/rest/v1/profiles?select=role&id=eq."+userId,null,accessToken);if(r.ok()){JSONArray a=new JSONArray(r.body);if(a.length()>0)role=a.getJSONObject(0).optString("role","member");}prefs.edit().putString("role",role).apply();main.post(this::dashboard);}catch(Exception e){main.post(this::dashboard);}}).start();}
    private void dashboard(){base("جمعياتي • لوحة التحكم");nav();LinearLayout c=box();c.addView(tv("مرحباً بك في نظام إدارة الجمعيات المالية",20,DARK));TextView stats=tv("جاري تحميل المؤشرات...",16,TEAL);c.addView(stats);content.addView(c);LinearLayout q=box();q.addView(tv("إجراءات سريعة",19,DARK));Button a=btn("إدارة الجمعيات"),m=btn("إدارة الأعضاء"),cy=btn("إدارة الدورات"),p=btn("تسجيل دفعة"),n=btn("عرض الإشعارات");q.addView(a);q.addView(m);q.addView(cy);q.addView(p);q.addView(n);content.addView(q);a.setOnClickListener(v->associations());m.setOnClickListener(v->members());cy.setOnClickListener(v->cycles());p.setOnClickListener(v->payments());n.setOnClickListener(v->notifications());Button out=btn("تسجيل الخروج");content.addView(out);out.setOnClickListener(v->logout());new Thread(()->{try{int ac=count("associations","owner_id=eq."+userId);int mm=count("association_members",null);int ii=count("installments",null);int late=count("installments","status=eq.late");main.post(()->stats.setText("الجمعيات: "+ac+"    الأعضاء: "+mm+"\nالأقساط: "+ii+"    المتأخرات: "+late+"\nالصلاحية: "+role));}catch(Exception e){main.post(()->stats.setText("تعذر تحميل المؤشرات"));}}).start();}
    private int count(String table,String filter)throws Exception{ApiResult r=req("GET","/rest/v1/"+table+"?select=id"+(filter==null?"":"&"+filter),null,accessToken);if(!r.ok())return 0;return new JSONArray(r.body).length();}
    private void associations(){base("الجمعيات");nav();LinearLayout f=box();f.addView(tv("إنشاء جمعية جديدة",19,DARK));EditText name=input("اسم الجمعية"),amount=input("قيمة القسط د.ل"),freq=input("التكرار: monthly / weekly / custom");freq.setText("monthly");f.addView(name);f.addView(amount);f.addView(freq);Button save=btn("حفظ");f.addView(save);content.addView(f);TextView list=tv("جاري التحميل...",15,DARK);content.addView(boxWith(list,"الجمعيات المسجلة"));save.setOnClickListener(v->{try{JSONObject j=new JSONObject();j.put("owner_id",userId);j.put("name",name.getText().toString().trim());j.put("installment",Double.parseDouble(amount.getText().toString().trim()));j.put("frequency",freq.getText().toString().trim());j.put("member_count",0);j.put("cycle_count",0);j.put("start_date",today());new Thread(()->{ApiResult r=req("POST","/rest/v1/associations",j.toString(),accessToken);main.post(()->{toast(r.ok()?"تم إنشاء الجمعية":"فشل إنشاء الجمعية: "+error(r.body));if(r.ok())associations();});}).start();}catch(Exception e){toast("أدخل بيانات صحيحة");}});loadAssociations(list);}
    private LinearLayout boxWith(View v,String h){LinearLayout b=box();b.addView(tv(h,18,DARK));b.addView(v);return b;}
    private void loadAssociations(TextView out){new Thread(()->{try{ApiResult r=req("GET","/rest/v1/associations?select=id,name,installment,frequency,member_count,cycle_count,start_date&owner_id=eq."+userId+"&order=created_at.desc",null,accessToken);StringBuilder s=new StringBuilder();if(r.ok()){JSONArray a=new JSONArray(r.body);for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);s.append("• ").append(x.optString("name")).append("\nID: ").append(x.optString("id")).append("\nالقسط: ").append(x.optString("installment")).append(" د.ل | ").append(x.optString("frequency")).append("\nالأعضاء: ").append(x.optInt("member_count")).append(" | الدورات: ").append(x.optInt("cycle_count")).append("\n\n");}}else s.append(error(r.body));main.post(()->out.setText(s.length()==0?"لا توجد جمعيات.":s.toString()));}catch(Exception e){main.post(()->out.setText("تعذر الاتصال"));}}).start();}
    private void members(){base("الأعضاء وترتيب الاستلام");nav();LinearLayout f=box();f.addView(tv("إضافة عضو إلى جمعية",19,DARK));EditText aid=input("معرّف الجمعية UUID"),uid=input("معرّف حساب العضو UUID"),ord=input("ترتيب الاستلام");f.addView(aid);f.addView(uid);f.addView(ord);Button b=btn("إضافة العضو");f.addView(b);content.addView(f);TextView out=tv("جاري التحميل...",14,DARK);content.addView(boxWith(out,"أعضاء الجمعيات"));b.setOnClickListener(v->{try{JSONObject j=new JSONObject();j.put("association_id",aid.getText().toString().trim());j.put("user_id",uid.getText().toString().trim());j.put("receiving_order",Integer.parseInt(ord.getText().toString().trim()));new Thread(()->{ApiResult r=req("POST","/rest/v1/association_members",j.toString(),accessToken);main.post(()->{toast(r.ok()?"تمت إضافة العضو":"فشل: "+error(r.body));if(r.ok())members();});}).start();}catch(Exception e){toast("تحقق من UUID والترتيب");}});new Thread(()->{try{ApiResult r=req("GET","/rest/v1/association_members?select=id,association_id,user_id,receiving_order,joined_at&order=receiving_order.asc",null,accessToken);main.post(()->out.setText(r.ok()?prettyArray(r.body):error(r.body)));}catch(Exception e){main.post(()->out.setText("تعذر التحميل"));}}).start();}
    private void cycles(){base("الدورات وترتيب المستفيدين");nav();LinearLayout f=box();f.addView(tv("إنشاء دورة",19,DARK));EditText aid=input("معرّف الجمعية UUID"),no=input("رقم الدورة"),bid=input("معرّف المستفيد UUID (اختياري)"),date=input("تاريخ الاستحقاق YYYY-MM-DD"),amount=input("مبلغ الدورة د.ل");f.addView(aid);f.addView(no);f.addView(bid);f.addView(date);f.addView(amount);Button b=btn("حفظ الدورة");f.addView(b);content.addView(f);TextView out=tv("جاري التحميل...",14,DARK);content.addView(boxWith(out,"الدورات"));b.setOnClickListener(v->{try{JSONObject j=new JSONObject();j.put("association_id",aid.getText().toString().trim());j.put("cycle_number",Integer.parseInt(no.getText().toString().trim()));String bu=bid.getText().toString().trim();if(!bu.isEmpty())j.put("beneficiary_user_id",bu);j.put("due_date",date.getText().toString().trim());j.put("amount",Double.parseDouble(amount.getText().toString().trim()));j.put("status","scheduled");new Thread(()->{ApiResult r=req("POST","/rest/v1/cycles",j.toString(),accessToken);main.post(()->{toast(r.ok()?"تم حفظ الدورة":"فشل: "+error(r.body));if(r.ok())cycles();});}).start();}catch(Exception e){toast("تحقق من البيانات");}});new Thread(()->{try{ApiResult r=req("GET","/rest/v1/cycles?select=id,association_id,cycle_number,beneficiary_user_id,due_date,amount,status&order=cycle_number.asc",null,accessToken);main.post(()->out.setText(r.ok()?prettyArray(r.body):error(r.body)));}catch(Exception e){main.post(()->out.setText("تعذر التحميل"));}}).start();}
    private void installments(){base("الأقساط والمتأخرات");nav();LinearLayout f=box();f.addView(tv("إضافة قسط",19,DARK));EditText cid=input("معرّف الدورة UUID"),mid=input("معرّف عضوية العضو UUID"),date=input("تاريخ الاستحقاق YYYY-MM-DD"),amount=input("المبلغ د.ل");f.addView(cid);f.addView(mid);f.addView(date);f.addView(amount);Button b=btn("حفظ القسط");f.addView(b);content.addView(f);TextView out=tv("جاري التحميل...",14,DARK);content.addView(boxWith(out,"آخر الأقساط"));b.setOnClickListener(v->{try{JSONObject j=new JSONObject();j.put("cycle_id",cid.getText().toString().trim());j.put("member_id",mid.getText().toString().trim());j.put("due_date",date.getText().toString().trim());j.put("amount",Double.parseDouble(amount.getText().toString().trim()));j.put("paid_amount",0);j.put("status","unpaid");new Thread(()->{ApiResult r=req("POST","/rest/v1/installments",j.toString(),accessToken);main.post(()->{toast(r.ok()?"تم حفظ القسط":"فشل: "+error(r.body));if(r.ok())installments();});}).start();}catch(Exception e){toast("تحقق من البيانات");}});new Thread(()->{try{ApiResult r=req("GET","/rest/v1/installments?select=id,cycle_id,member_id,due_date,amount,paid_amount,status,receipt_no&order=due_date.desc&limit=100",null,accessToken);main.post(()->out.setText(r.ok()?prettyArray(r.body):error(r.body)));}catch(Exception e){main.post(()->out.setText("تعذر التحميل"));}}).start();}
    private void payments(){base("الدفعات والإيصالات");nav();LinearLayout f=box();f.addView(tv("تسجيل دفعة",19,DARK));EditText iid=input("معرّف القسط UUID"),mid=input("معرّف العضوية UUID"),amount=input("المبلغ المدفوع د.ل"),notes=input("ملاحظات");f.addView(iid);f.addView(mid);f.addView(amount);f.addView(notes);Button b=btn("تسجيل الدفعة وإصدار إيصال");f.addView(b);content.addView(f);TextView out=tv("جاري التحميل...",14,DARK);content.addView(boxWith(out,"آخر الدفعات"));b.setOnClickListener(v->{try{double am=Double.parseDouble(amount.getText().toString().trim());String receipt="JAM-"+System.currentTimeMillis();JSONObject j=new JSONObject();j.put("p_installment_id",iid.getText().toString().trim());j.put("p_member_id",mid.getText().toString().trim());j.put("p_amount",am);j.put("p_receipt_no",receipt);j.put("p_notes",notes.getText().toString());new Thread(()->{try{ApiResult r=req("POST","/rest/v1/rpc/record_payment",j.toString(),accessToken);main.post(()->{toast(r.ok()?"تم تسجيل الدفعة وإصدار الإيصال":"فشل: "+error(r.body));if(r.ok())payments();});}catch(Exception e){main.post(()->toast("تعذر تسجيل الدفعة: "+e.getMessage()));}}).start();}catch(Exception e){toast("تحقق من البيانات");}});new Thread(()->{try{ApiResult r=req("GET","/rest/v1/payments?select=id,installment_id,member_id,amount,paid_at,receipt_no,notes&order=paid_at.desc&limit=100",null,accessToken);main.post(()->out.setText(r.ok()?prettyArray(r.body):error(r.body)));}catch(Exception e){main.post(()->out.setText("تعذر التحميل"));}}).start();}
    private void notifications(){base("الإشعارات");nav();TextView out=tv("جاري التحميل...",15,DARK);content.addView(boxWith(out,"التنبيهات"));Button gen=btn("توليد تنبيهات الأقساط الآن");content.addView(gen);gen.setOnClickListener(v->new Thread(()->{ApiResult r=req("POST","/rest/v1/rpc/generate_due_notifications","{}",accessToken);main.post(()->{toast(r.ok()?"تم توليد التنبيهات":"تعذر التوليد: "+error(r.body));loadNotifications(out);});}).start());loadNotifications(out);}
    private void loadNotifications(TextView out){new Thread(()->{try{ApiResult r=req("GET","/rest/v1/notifications?select=id,title,body,notification_type,read_at,created_at&user_id=eq."+userId+"&order=created_at.desc&limit=100",null,accessToken);main.post(()->out.setText(r.ok()?prettyArray(r.body):error(r.body)));}catch(Exception e){main.post(()->out.setText("تعذر التحميل"));}}).start();}
    private void reports(){base("التقارير");nav();LinearLayout b=box();b.addView(tv("تقارير النظام",20,DARK));b.addView(tv("يمكنك إنشاء تقرير PDF ملخص أو ملف CSV قابل للفتح في Excel.",14,Color.GRAY));Button pdf=btn("إنشاء تقرير PDF"),csv=btn("إنشاء تقرير CSV");b.addView(pdf);b.addView(csv);content.addView(b);pdf.setOnClickListener(v->makePdf());csv.setOnClickListener(v->makeCsv());}
    private void makePdf(){new Thread(()->{try{ApiResult a=req("GET","/rest/v1/associations?select=name,installment,member_count,cycle_count&owner_id=eq."+userId,null,accessToken);String text="تقرير جمعياتي\n\nتاريخ: "+today()+"\n\n"+prettyArray(a.body);File f=new File(getExternalFilesDir(null),"jam3yati_report.pdf");PdfDocument d=new PdfDocument();PdfDocument.Page p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=p.getCanvas();Paint paint=new Paint();paint.setTextSize(14);int y=50;for(String line:text.split("\n")){c.drawText(line,560,y,paint);y+=22;if(y>800){d.finishPage(p);p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,2).create());c=p.getCanvas();y=50;}}d.finishPage(p);FileOutputStream os=new FileOutputStream(f);d.writeTo(os);os.close();d.close();main.post(()->shareFile(f,"application/pdf"));}catch(Exception e){main.post(()->toast("فشل إنشاء PDF: "+e.getMessage()));}}).start();}
    private void makeCsv(){new Thread(()->{try{ApiResult r=req("GET","/rest/v1/associations?select=id,name,installment,frequency,member_count,cycle_count,start_date&owner_id=eq."+userId,null,accessToken);File f=new File(getExternalFilesDir(null),"jam3yati_report.csv");FileWriter w=new FileWriter(f);w.write("id,name,installment,frequency,member_count,cycle_count,start_date\n");if(r.ok()){JSONArray a=new JSONArray(r.body);for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);w.write(csv(x.optString("id"))+","+csv(x.optString("name"))+","+x.optString("installment")+","+x.optString("frequency")+","+x.optInt("member_count")+","+x.optInt("cycle_count")+","+x.optString("start_date")+"\n");}}w.close();main.post(()->shareFile(f,"text/csv"));}catch(Exception e){main.post(()->toast("فشل إنشاء CSV: "+e.getMessage()));}}).start();}
    private String csv(String s){return "\"" + s.replace("\"", "\"\"") + "\"";}
    private void shareFile(File f,String type){try{Uri uri=FileProvider.getUriForFile(this,"com.jam3yati.app.fileprovider",f);Intent send=new Intent(Intent.ACTION_SEND);send.setType(type);send.putExtra(Intent.EXTRA_STREAM,uri);send.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);send.setClipData(ClipData.newRawUri("report",uri));startActivity(Intent.createChooser(send,"مشاركة التقرير"));}catch(Exception e){toast("تم إنشاء التقرير، وتعذر فتح المشاركة: "+e.getMessage());}}
    private void logout(){prefs.edit().clear().apply();accessToken="";userId="";role="member";login();}
    private String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
    private String prettyArray(String body){try{JSONArray a=new JSONArray(body);StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);Iterator<String> it=o.keys();while(it.hasNext()){String k=it.next();s.append(k).append(": ").append(o.optString(k)).append(" | ");}s.append("\n\n");}return s.length()==0?"لا توجد بيانات":s.toString();}catch(Exception e){return body;}}
    private ApiResult req(String method,String path,String body,String token)throws Exception{URL u=new URL(SUPABASE_URL+path);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("apikey",SUPABASE_KEY);c.setRequestProperty("Accept","application/json");c.setRequestProperty("Prefer","return=representation");if(token!=null&&!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.getOutputStream().write(body.getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream is=code>=400?c.getErrorStream():c.getInputStream();String out="";if(is!=null){BufferedReader br=new BufferedReader(new InputStreamReader(is,StandardCharsets.UTF_8));String line;StringBuilder s=new StringBuilder();while((line=br.readLine())!=null)s.append(line);out=s.toString();br.close();}c.disconnect();return new ApiResult(code,out);}
    private String error(String b){try{JSONObject j=new JSONObject(b);return j.optString("message",j.optString("msg",j.optString("error_description",b)));}catch(Exception e){return b;}}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private static class ApiResult{int code;String body;ApiResult(int c,String b){code=c;body=b;}boolean ok(){return code>=200&&code<300;}}
}